### ISSUE TITLE
Translation to Brazilian Portuguese

### ISSUE THREAD

**Issue by valdecircarvalho** [baldsealion/Steam-Deck-Ultimate-Windows-Guide#4]
Hello there!
First of all, thank you so much for putting this guide together. It is the BEST/Most Complete/Detailed guide about how to Install Windows on the Deck. 
I'm a Deck enthusiast living in Brazil and I have come up with a Steam Deck Guide in Portuguese [Guia do Steam Deck](https://guiadosteamdeck.com.br/) for my fellow Brazilians who couldn't read in English. I would like to check if you are willing to let me translate your content. I don't need to publish on my website, I can publish it here and just link to your website.
Cheers!
--VC

**Comment by baldsealion** [comment]
Thank you very much!

Yes you can definitely translate it. I appreciate you asking.
